/**
* This file was @generated using pocketbase-typegen
*/

import type PocketBase from 'pocketbase'
import type { RecordService } from 'pocketbase'

export const Collections = {
	Authorigins: "_authOrigins",
	Externalauths: "_externalAuths",
	Mfas: "_mfas",
	Otps: "_otps",
	Superusers: "_superusers",
	Archive: "archive",
	Episodes: "episodes",
	Genres: "genres",
	Hosts: "hosts",
	ObsAgents: "obs_agents",
	Programmes: "programmes",
	Settings: "settings",
	Shows: "shows",
	Users: "users",
} as const
export type Collections = typeof Collections[keyof typeof Collections]

// Alias types for improved usability
export type IsoDateString = string
export type IsoAutoDateString = string & { readonly autodate: unique symbol }
export type RecordIdString = string
export type FileNameString = string & { readonly filename: unique symbol }
export type HTMLString = string

type ExpandType<T> = unknown extends T
	? T extends unknown
		? { expand?: unknown }
		: { expand: T }
	: { expand: T }

// System fields
export type BaseSystemFields<T = unknown> = {
	id: RecordIdString
	collectionId: string
	collectionName: Collections
} & ExpandType<T>

export type AuthSystemFields<T = unknown> = {
	email: string
	emailVisibility: boolean
	username: string
	verified: boolean
} & BaseSystemFields<T>

// Record types for each collection

export type AuthoriginsRecord = {
	collectionRef: string
	created: IsoAutoDateString
	fingerprint: string
	id: string
	recordRef: string
	updated: IsoAutoDateString
}

export type ExternalauthsRecord = {
	collectionRef: string
	created: IsoAutoDateString
	id: string
	provider: string
	providerId: string
	recordRef: string
	updated: IsoAutoDateString
}

export type MfasRecord = {
	collectionRef: string
	created: IsoAutoDateString
	id: string
	method: string
	recordRef: string
	updated: IsoAutoDateString
}

export type OtpsRecord = {
	collectionRef: string
	created: IsoAutoDateString
	id: string
	password: string
	recordRef: string
	sentTo?: string
	updated: IsoAutoDateString
}

export type SuperusersRecord = {
	created: IsoAutoDateString
	email: string
	emailVisibility?: boolean
	id: string
	password: string
	tokenKey: string
	updated: IsoAutoDateString
	verified?: boolean
}

export const ArchiveStatusOptions = {
	"draft": "draft",
	"published": "published",
} as const
export type ArchiveStatusOptions = typeof ArchiveStatusOptions[keyof typeof ArchiveStatusOptions]
export type ArchiveRecord<TmediaLinks = unknown> = {
	createdBy?: RecordIdString
	endTime?: IsoDateString
	episode?: RecordIdString
	genres?: RecordIdString[]
	id: string
	image?: FileNameString
	mediaLinks?: null | TmediaLinks
	notes?: HTMLString
	programme?: RecordIdString
	show?: RecordIdString
	startTime?: IsoDateString
	status: ArchiveStatusOptions
	title?: string
}

export const EpisodesStatusOptions = {
	"draft": "draft",
	"scheduled": "scheduled",
	"live": "live",
	"completed": "completed",
	"cancelled": "cancelled",
} as const
export type EpisodesStatusOptions = typeof EpisodesStatusOptions[keyof typeof EpisodesStatusOptions]

export const EpisodesLivestreamOverrideOptions = {
	"inherit": "inherit",
	"live": "live",
	"skip": "skip",
} as const
export type EpisodesLivestreamOverrideOptions = typeof EpisodesLivestreamOverrideOptions[keyof typeof EpisodesLivestreamOverrideOptions]
export type EpisodesRecord = {
	cancelReason?: string
	createdBy?: RecordIdString
	endTime: IsoDateString
	genres?: RecordIdString[]
	hosts?: RecordIdString
	id: string
	image?: FileNameString
	isAutoGenerated?: boolean
	livestream_override?: EpisodesLivestreamOverrideOptions
	notes?: HTMLString
	programme?: RecordIdString
	show?: RecordIdString
	startTime: IsoDateString
	status: EpisodesStatusOptions
	title?: string
}

export type GenresRecord = {
	color?: string
	id: string
	name: string
	slug?: string
}

export type HostsRecord<Tsocials = unknown> = {
	avatar?: FileNameString
	bio?: HTMLString
	createdBy?: RecordIdString
	id: string
	name: string
	reminderDays?: number
	socials?: null | Tsocials
	userId?: RecordIdString
}

export const ObsAgentsModeOptions = {
	"auto": "auto",
	"override": "override",
	"disable": "disable",
} as const
export type ObsAgentsModeOptions = typeof ObsAgentsModeOptions[keyof typeof ObsAgentsModeOptions]
export type ObsAgentsRecord<TalertState = unknown, TchannelsEnabled = unknown, Tcommand = unknown, TcommandAck = unknown, TcurrentShow = unknown, TnextShow = unknown, Toverrides = unknown, Tschedule = unknown> = {
	activeLocal?: boolean
	agentVersion?: string
	alertState?: null | TalertState
	autostart?: boolean
	boxId: string
	channelId?: number
	channelsEnabled?: null | TchannelsEnabled
	command?: null | Tcommand
	commandAck?: null | TcommandAck
	currentShow?: null | TcurrentShow
	currentShowId?: string
	email: string
	emailVisibility?: boolean
	heartbeatAt?: number
	id: string
	lastTickAt?: number
	mode?: ObsAgentsModeOptions
	name?: string
	nextShow?: null | TnextShow
	node?: string
	obsExePath?: string
	obsLaunchLeadSec?: number
	obsRunning?: boolean
	obsWsUrl?: string
	overrides?: null | Toverrides
	password: string
	pausedLocal?: boolean
	platform?: string
	recordLeadSec?: number
	recording?: boolean
	schedule?: null | Tschedule
	scheduleFetchedAt?: number
	scheduleUrl?: string
	stopGraceSec?: number
	streaming?: boolean
	tokenKey: string
	verified?: boolean
}

export type ProgrammesRecord = {
	channelId?: number
	color?: string
	editors?: RecordIdString
	id: string
	livestream?: boolean
	name: string
	slug?: string
}

export type SettingsRecord = {
	id: string
	reminderEmailBody?: string
	reminderEmailSubject?: string
}

export type ShowsRecord<TrecurrenceRule = unknown> = {
	artwork?: FileNameString
	color?: string
	createdBy?: RecordIdString
	description?: HTMLString
	genres?: RecordIdString[]
	hosts?: RecordIdString
	id: string
	programme?: RecordIdString
	recurrenceRule?: null | TrecurrenceRule
	title: string
}

export const UsersRoleOptions = {
	"admin": "admin",
	"editor": "editor",
	"member": "member",
	"viewer": "viewer",
} as const
export type UsersRoleOptions = typeof UsersRoleOptions[keyof typeof UsersRoleOptions]
export type UsersRecord = {
	email: string
	emailVisibility?: boolean
	id: string
	name?: string
	password: string
	role: UsersRoleOptions
	tokenKey: string
	verified?: boolean
	zitadelId?: string
}

// Response types include system fields and match responses from the PocketBase API
export type AuthoriginsResponse<Texpand = unknown> = Required<AuthoriginsRecord> & BaseSystemFields<Texpand>
export type ExternalauthsResponse<Texpand = unknown> = Required<ExternalauthsRecord> & BaseSystemFields<Texpand>
export type MfasResponse<Texpand = unknown> = Required<MfasRecord> & BaseSystemFields<Texpand>
export type OtpsResponse<Texpand = unknown> = Required<OtpsRecord> & BaseSystemFields<Texpand>
export type SuperusersResponse<Texpand = unknown> = Required<SuperusersRecord> & AuthSystemFields<Texpand>
export type ArchiveResponse<TmediaLinks = unknown, Texpand = unknown> = Required<ArchiveRecord<TmediaLinks>> & BaseSystemFields<Texpand>
export type EpisodesResponse<Texpand = unknown> = Required<EpisodesRecord> & BaseSystemFields<Texpand>
export type GenresResponse<Texpand = unknown> = Required<GenresRecord> & BaseSystemFields<Texpand>
export type HostsResponse<Tsocials = unknown, Texpand = unknown> = Required<HostsRecord<Tsocials>> & BaseSystemFields<Texpand>
export type ObsAgentsResponse<TalertState = unknown, TchannelsEnabled = unknown, Tcommand = unknown, TcommandAck = unknown, TcurrentShow = unknown, TnextShow = unknown, Toverrides = unknown, Tschedule = unknown, Texpand = unknown> = Required<ObsAgentsRecord<TalertState, TchannelsEnabled, Tcommand, TcommandAck, TcurrentShow, TnextShow, Toverrides, Tschedule>> & AuthSystemFields<Texpand>
export type ProgrammesResponse<Texpand = unknown> = Required<ProgrammesRecord> & BaseSystemFields<Texpand>
export type SettingsResponse<Texpand = unknown> = Required<SettingsRecord> & BaseSystemFields<Texpand>
export type ShowsResponse<TrecurrenceRule = unknown, Texpand = unknown> = Required<ShowsRecord<TrecurrenceRule>> & BaseSystemFields<Texpand>
export type UsersResponse<Texpand = unknown> = Required<UsersRecord> & AuthSystemFields<Texpand>

// Types containing all Records and Responses, useful for creating typing helper functions

export type CollectionRecords = {
	_authOrigins: AuthoriginsRecord
	_externalAuths: ExternalauthsRecord
	_mfas: MfasRecord
	_otps: OtpsRecord
	_superusers: SuperusersRecord
	archive: ArchiveRecord
	episodes: EpisodesRecord
	genres: GenresRecord
	hosts: HostsRecord
	obs_agents: ObsAgentsRecord
	programmes: ProgrammesRecord
	settings: SettingsRecord
	shows: ShowsRecord
	users: UsersRecord
}

export type CollectionResponses = {
	_authOrigins: AuthoriginsResponse
	_externalAuths: ExternalauthsResponse
	_mfas: MfasResponse
	_otps: OtpsResponse
	_superusers: SuperusersResponse
	archive: ArchiveResponse
	episodes: EpisodesResponse
	genres: GenresResponse
	hosts: HostsResponse
	obs_agents: ObsAgentsResponse
	programmes: ProgrammesResponse
	settings: SettingsResponse
	shows: ShowsResponse
	users: UsersResponse
}

// Utility types for create/update operations

type ProcessCreateAndUpdateFields<T> = Omit<{
	// Omit AutoDate fields
	[K in keyof T as Extract<T[K], IsoAutoDateString> extends never ? K : never]: 
		// Convert FileNameString to File
		T[K] extends infer U ? 
			U extends (FileNameString | FileNameString[]) ? 
				U extends any[] ? File[] : File 
			: U
		: never
}, 'id'>

// Create type for Auth collections
export type CreateAuth<T> = {
	id?: RecordIdString
	email: string
	emailVisibility?: boolean
	password: string
	passwordConfirm: string
	verified?: boolean
} & ProcessCreateAndUpdateFields<T>

// Create type for Base collections
export type CreateBase<T> = {
	id?: RecordIdString
} & ProcessCreateAndUpdateFields<T>

// Update type for Auth collections
export type UpdateAuth<T> = Partial<
	Omit<ProcessCreateAndUpdateFields<T>, keyof AuthSystemFields>
> & {
	email?: string
	emailVisibility?: boolean
	oldPassword?: string
	password?: string
	passwordConfirm?: string
	verified?: boolean
}

// Update type for Base collections
export type UpdateBase<T> = Partial<
	Omit<ProcessCreateAndUpdateFields<T>, keyof BaseSystemFields>
>

// Get the correct create type for any collection
export type Create<T extends keyof CollectionResponses> =
	CollectionResponses[T] extends AuthSystemFields
		? CreateAuth<CollectionRecords[T]>
		: CreateBase<CollectionRecords[T]>

// Get the correct update type for any collection
export type Update<T extends keyof CollectionResponses> =
	CollectionResponses[T] extends AuthSystemFields
		? UpdateAuth<CollectionRecords[T]>
		: UpdateBase<CollectionRecords[T]>

// Type for usage with type asserted PocketBase instance
// https://github.com/pocketbase/js-sdk#specify-typescript-definitions

export type TypedPocketBase = {
	collection<T extends keyof CollectionResponses>(
		idOrName: T
	): RecordService<CollectionResponses[T]>
} & PocketBase
